import 'capacity_policy.dart';
import 'residency_class.dart';
import 'track_identity.dart';

/// One row of a [SyncManifest] — a single track the desktop wants
/// the phone to hold. Carries enough metadata for the phone to:
///   - decide what to download and what's already cached,
///   - display title/artist/duration without a separate metadata sync,
///   - choose eviction targets when capacity tightens.
class ManifestEntry {
  final TrackIdentity identity;

  /// Display metadata. Snapshot of the moment the manifest was
  /// generated. Phone uses this for UI; phone does NOT mutate
  /// titles/artists/etc. — desktop is the source of truth.
  final String title;
  final String artist;
  final int durationMs;

  /// Transport variant being shipped — the bytes the phone will
  /// download via `GET /api/v1/track/:variant_id`. Wire values:
  /// `'mp3'` (Slice 1), `'aac_256'` / `'opus_128'` / etc. (Slice 3+).
  ///
  /// The URL keys off `variant_id` (the desktop's `Track.uid`)
  /// rather than `intel_uid` so transport resolution stays
  /// deterministic when multiple variants of the same song exist:
  /// the phone always GETs exactly the bytes the manifest told it
  /// to expect.
  final String transportFormat;

  /// Size in bytes of the transport variant. Sum across entries =
  /// total bytes the phone will hold. Used for storage-budget
  /// capacity math and for HTTP Content-Length on the download.
  final int byteSize;

  /// Integrity hash for the bytes the phone will receive at
  /// `GET /api/v1/track/:variant_id`. Phone re-hashes received
  /// bytes and rejects mismatches — protects against corruption
  /// in transit, wrong-file-shipped bugs, or stale transcode
  /// cache serving the wrong content.
  ///
  /// Slice 1: equal to the desktop's `Track.contentHash` (the
  /// 512KB heuristic hash) since MP3 passthrough ships the
  /// original bytes. Slice 3+ swaps to a full sha256 of the
  /// transcoded file when transport cache lights up.
  ///
  /// Kept as a non-optional field from day one because adding
  /// integrity verification later means schema migration on the
  /// wire — front-loading it now is cheap.
  final String transportHash;

  /// Residency policy for this entry. Determines eviction
  /// eligibility on the phone side.
  final ResidencyClass residency;

  /// Lower = evict first when capacity tightens. Generated by the
  /// desktop's manifest builder via the active sync recipe.
  final int priorityRank;

  /// `tracks.favorite` snapshot at manifest time. Phone can render
  /// the star without a separate state fetch; favorite mutations
  /// still flow back as telemetry events.
  final bool favorite;

  /// `tracks.reviewed_at` snapshot. Phone uses this to drive the
  /// "Heard this before" prompt when a track that was previously
  /// reviewed lands back in rotation.
  final int? reviewedAt;

  const ManifestEntry({
    required this.identity,
    required this.title,
    required this.artist,
    required this.durationMs,
    required this.transportFormat,
    required this.byteSize,
    required this.transportHash,
    required this.residency,
    required this.priorityRank,
    required this.favorite,
    this.reviewedAt,
  });

  Map<String, Object?> toJson() => {
        'identity': identity.toJson(),
        'title': title,
        'artist': artist,
        'duration_ms': durationMs,
        'transport_format': transportFormat,
        'byte_size': byteSize,
        'transport_hash': transportHash,
        'residency': residency.wireName,
        'priority_rank': priorityRank,
        'favorite': favorite,
        if (reviewedAt != null) 'reviewed_at': reviewedAt,
      };

  static ManifestEntry fromJson(Map<String, Object?> j) {
    final identity = j['identity'];
    if (identity is! Map<String, Object?>) {
      throw const FormatException('ManifestEntry.identity missing');
    }
    final transportHash = j['transport_hash'];
    if (transportHash is! String || transportHash.isEmpty) {
      throw const FormatException('ManifestEntry.transport_hash required');
    }
    return ManifestEntry(
      identity: TrackIdentity.fromJson(identity),
      title: (j['title'] as String?) ?? '',
      artist: (j['artist'] as String?) ?? '',
      durationMs: _asInt(j['duration_ms']) ?? 0,
      transportFormat: (j['transport_format'] as String?) ?? 'mp3',
      byteSize: _asInt(j['byte_size']) ?? 0,
      transportHash: transportHash,
      residency:
          ResidencyClass.fromWire((j['residency'] as String?) ?? 'rotating'),
      priorityRank: _asInt(j['priority_rank']) ?? 0,
      favorite: (j['favorite'] as bool?) ?? false,
      reviewedAt: _asInt(j['reviewed_at']),
    );
  }
}

/// The atomic sync unit. Generated by the desktop's
/// `MobileManifestBuilder` per device, per sync request. Phone diffs
/// its local inventory against the entries list → computes need_add /
/// need_remove / unchanged.
///
/// `manifestVersion` is monotonic per (desktop, device). The phone
/// holds `last_manifest_version` locally; the next handshake sends
/// it as a delta hint so the desktop can short-circuit serving
/// unchanged content (Slice 2+).
class SyncManifest {
  final int manifestVersion;
  final String deviceId;
  final int generatedAt;
  final CapacityPolicy capacity;
  final List<ManifestEntry> entries;

  const SyncManifest({
    required this.manifestVersion,
    required this.deviceId,
    required this.generatedAt,
    required this.capacity,
    required this.entries,
  });

  Map<String, Object?> toJson() => {
        'manifest_version': manifestVersion,
        'device_id': deviceId,
        'generated_at': generatedAt,
        'capacity': capacity.toJson(),
        'entries': [for (final e in entries) e.toJson()],
      };

  static SyncManifest fromJson(Map<String, Object?> j) {
    final version = _asInt(j['manifest_version']);
    final deviceId = j['device_id'];
    final generatedAt = _asInt(j['generated_at']);
    final capacity = j['capacity'];
    final entries = j['entries'];
    if (version == null) {
      throw const FormatException('SyncManifest.manifest_version required');
    }
    if (deviceId is! String) {
      throw const FormatException('SyncManifest.device_id required');
    }
    if (generatedAt == null) {
      throw const FormatException('SyncManifest.generated_at required');
    }
    if (capacity is! Map<String, Object?>) {
      throw const FormatException('SyncManifest.capacity required');
    }
    if (entries is! List) {
      throw const FormatException('SyncManifest.entries required (list)');
    }
    return SyncManifest(
      manifestVersion: version,
      deviceId: deviceId,
      generatedAt: generatedAt,
      capacity: CapacityPolicy.fromJson(capacity),
      entries: [
        for (final e in entries)
          ManifestEntry.fromJson(e as Map<String, Object?>),
      ],
    );
  }
}

int? _asInt(Object? v) {
  if (v == null) return null;
  if (v is int) return v;
  if (v is num) return v.toInt();
  if (v is String) return int.tryParse(v);
  return null;
}
