/// Transient operational narration for "what just happened in the
/// library" after a scan reconciles file presence.
///
/// Generated by `LibraryController._surfaceReconciliationSummary`
/// when a scan flips a non-trivial number of rows from available →
/// missing. The reconciliation banner widget renders this as a
/// calm, non-modal toast above the status bar:
///
///   Q removed
///   38 preserved through other folders
///   142 tracks removed from view
///
/// **Ordering rule** (load-bearing UX choice): the banner renders
/// `preservedElsewhere` BEFORE `removed`. Users emotionally anchor
/// to loss first; leading with the survival number reframes the
/// operation as a curated workflow step rather than data loss.
class ReconciliationSummary {
  /// User-facing label of the source whose scan produced this
  /// reconciliation. Drives the banner heading ("Q removed").
  final String sourceName;

  /// Number of indexed_files rows in this source that transitioned
  /// from `available` to `missing` during the scan. Each one
  /// disappears from the visible table because of the
  /// "removed-from-disk = removed-from-view" policy.
  final int removed;

  /// Subset of [removed] whose `content_hash` still appears on at
  /// least one available row in a different watched source. From
  /// the user's perspective, these tracks "survived through other
  /// folders" — their intel (favorite, play count, review state)
  /// stays reachable through the surviving variant.
  final int preservedElsewhere;

  /// Wall-clock time the summary was generated. Used as an
  /// identity token so the auto-dismiss timer can verify it's
  /// dismissing the same summary it was created for (race
  /// between a fresh summary landing and an older timer firing).
  final DateTime surfacedAt;

  const ReconciliationSummary({
    required this.sourceName,
    required this.removed,
    required this.preservedElsewhere,
    required this.surfacedAt,
  });
}
